[package]
name = "notify-remote"
version = "0.1.0"
authors = ["Silcet"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
